image: archlinux
packages:
    - elixir
    - erlang
    - zig
    - 7zip

sources:
    - https://git.sr.ht/~naginikaido/nitory-reborn
  
tasks:
    - setup: |
        case "$GIT_REF" in
             "refs/heads/main")
                exit 0
                ;;
             "refs/tags/"*)
                exit 0
                ;;
             *)
                ;;
        esac
        export LC_ALL=en_US.UTF-8
        cd nitory-reborn
        git checkout $GIT_REF
        mix local.hex --force
        mix deps.get
    - test: |
        case "$GIT_REF" in
             "refs/heads/main")
                exit 0
                ;;
             "refs/tags/"*)
                exit 0
                ;;
             *)
                ;;
        esac
        export LC_ALL=en_US.UTF-8
        cd nitory-reborn
        git checkout $GIT_REF
        mix test
              
triggers:
    - action: email
      condition: failure
      to: NagiNikaido <naginikaido@kuusouhakuchuu.cn>

submitter:
    git.sr.ht:
        enabled: true

